#!/bin/sh
# Thin wrapper around ibrun on Ranger so that it looks enough
# like an mpirun command to keep gasnetrun_mpi happy (and indirectly
# gasnetrun_ibv).
# It is also possible to use this directly as the CONDUIT_RUNCMD
# for mpi- and ibv-conduits on Ranger, or as the mpi_spawn and
# ibv_spawn settings with Berkeley UPC.
# -PHH 2009.03.06
case "$1" in
  -h) 
    # For gasnetrun_mpi's probe
    echo "wrapper for ibrun"
    exit 0
    ;;
  -np)
    # The ibrun spawner always runs with the full submit-time geometery
    # XXX: We should check that the argument matches the job geometry!
    #export MY_NSLOTS=$2 doesn't work quite right
    shift; shift;  # Remove "-np N"
    ;;
  -*)
    echo "unknown option $1"
    exit 1
    ;;
esac
unset MALLOC_CHECK_ # Don't know why, but this env var fouls up ibrun!
exec ibrun "$@"
