#!/bin/sh
# Thin wrapper around ibrun on Ranger so that it looks enough
# like an mpirun command to keep gasnetrun_mpi happy (and indirectly
# gasnetrun_ibv).
# It is also possible to use this directly as the CONDUIT_RUNCMD
# for mpi- and ibv-conduits on Ranger, or as the mpi_spawn and
# ibv_spawn settings with Berkeley UPC.
# -PHH 2009.03.06
# $Id: gasnet_ibrun,v 1.4 2009/03/23 19:41:32 yzheng Exp $
case "$1" in
  -h) 
    # For gasnetrun_mpi's probe
    echo "wrapper for ibrun"
    exit 0
    ;;
  -np)
    MY_NSLOTS=$2
    export MY_NSLOTS
    shift; shift;  # Remove "-np N"
    ;;
  -*)
    echo "unknown option $1"
    exit 1
    ;;
esac
# Don'yet t know why, but this env var fouls up ibrun!
unset MALLOC_CHECK_
# Increase the IB-level timeout to match the one TACC uses for MPI
# This value is a bit-shift, and thus results in a timeout that is
# 32 times larger than our default value 18.
GASNET_QP_TIMEOUT=23
export GASNET_QP_TIMEOUT
#
exec ibrun tacc_affinity "$@"
